name: CluedIn.Nuget-Installer-$(Build.BuildId)

trigger:
- master

strategy:
  maxParallel: 2
  matrix:
    Win2018:
      windowsBaseTag: '1803'
      pool: 'win1803'
    Win2019:
      windowsBaseTag: '1809'
      pool: 'windows-2019'
pool:
  vmImage: '$(pool)'

steps:
- task: Docker@2
  displayName: "Build image"
  inputs:
    containerRegistry: 'Docker Hub'
    repository: cluedin/nuget-installer
    command: build
    tags: $(windowsBaseTag)-latest
    arguments: --build-arg VERSION=$(windowsBaseTag)

- task: Docker@2
  displayName: "Push image"
  inputs:
    containerRegistry: 'Docker Hub'
    repository: cluedin/nuget-installer
    command: push
    tags: $(windowsBaseTag)-latest
